### ISSUE TITLE
UI testing: issues

### ISSUE THREAD

**Issue by FlorianCassayre** [inveniosoftware/react-invenio-app-ils#172]
## Backoffice

  - Any form that uses a "search document/location" component:
    - [x] When no result is found the dropdown stays visible, even when the field loses focus. Actually the only way to get rid of the message is to make a selection. (fixed by #217)
    - [x] The auto-completion does not work as the user intends it to: it expects full keywords rather than just prefixes  (fixed by #217)
  - Document/Series/Item/... forms:
    - [x] No error message is displayed if the server is down (see also inveniosoftware/invenio-app-ils#855) (fixed by #220)
    - [x] ~The error tooltip on fields is displayed on top, messing the alignment~ (see #169)
    - [x] ~The price field does not match the server schema~ (see #155)
    - [x] The "Navigation" menu does not have an initial value before scrolling (fixed by #180)
    - [x] Some elements define a `"tabindex"="0"` and are initially focused, but actually appear in the middle of the page (fixed by #180)
    - [x] Frontend error when viewing the page from a mobile device (fixed by #180)
    - [x] The cross icon (keywords, authors, ...) appears on top of everything else, including an expanded dropdown(fixed by #216)
  - Search:
    - [x] Search result exportation doesn't work (fixed by #180)
  - Document search:
    - [x] ~When clicking on a tag (Drama, Thriller, etc.), the url is updated but nothing happens unless the page is reloaded~ (see #196)
    - [x] ~Start with an empty search, click on a tag, and go back a page: the search provides an empty result set (again, unless if the page is reloaded)~ (see #196)
  - Document:
    - [x] In the "Request loan for a patron" modal, the "Request" button is not disabled when no patron is provided (fixed by #180)
    - [x] When in document details, the button `Request loan for Patron` in `DocumentActionMenu`, throws an error: `locationPid` is marked as required in `LocationDatePicker`, but its value is `null`. The input for the date is disabled until we select a patron with a `locationPid`, maybe we can prevent rendering the calendar until we have a `locationPid`(fixed by #216)
  - Loans:
    - [x] Frontsite error after clicking on the "Replace" button ([trace](https://user-images.githubusercontent.com/9027075/90262901-361eeb00-de4f-11ea-9ea3-1ea01b6e98be.png)) (fixed by #180)
    - [x] ~"Send return reminder", is not working for overdue loans (it returns a 400 saying "This loan is not overdue")~ (see #204)
  - Item:
    - [x] The checkout buttons are in loading state but not disabled, they can still be clicked and will throw errors (I believe it is my fault) (fixed by #180)
    - [x] ~A malicious librarian can leave the database/index in an inconsistent state by allocating two distinct loans the same item. This can be reproduced by opening the page on two different tabs, and rapidly clicking on the two checkout buttons. After that the server detects the inconsistency (`MultipleLoansOnItemError`) but cannot recover from it~ (see inveniosoftware/invenio-circulation#120)
  - Series:
    - [x] ~On the edition/creation form, the author component has performance issues when typing in it. This comes from a more general problem that affects all `<StringField />` components due to a slow `onChange` method handler~ (see #218)
  - ILL:
    - [x] Borrowing request modal (button "New loan"): select an end date, the "Create" button should enable, close the modal and reopen it; the "Create" button is still enabled despite no end date being selected (fixed by #180)
  - Patrons: 
    - [x] ILL in patron profile is not displayed correctly (consider split the title in 2 lines). (fixed by #215)
      <details>

      ![image](https://user-images.githubusercontent.com/15194802/94691054-23923f80-0331-11eb-930c-06aebe8c673a.png)

      </details>

  - Overview:
    - [x] ~Button "Send reminder" is not disabled if the loan is not overdue. Same problem on the loan page, but with no error feedback this time~ (see #204)

## Frontsite
  - Search
    - [x] ~When performing a global search from the homepage, the pagination does not show any page to be selected. After that, when clicking on "1" to select the first page the result changes~ (see #196)
    - [x] Error message is not correctly aligned when getting 429 errors (too many requests).
      <details>

      ![image](https://user-images.githubusercontent.com/15194802/94690782-d01ff180-0330-11eb-8365-caebd9e2115f.png)

      </details>
  - Patron profile ("My loans"):
    - [x] Superfluous navigation buttons when there is clearly zero entries (fixed by #180)
  - Document/series page:
    - [x] The frontend raises an error if the server is down (reason is that `error.response` is not necessarily set) (fixed by #179)
  - Login page:
    - [x] The dimmer only prevents the user from interacting with the input using their mouse, but not with their keyboard (ie. typing stuff) (see also Semantic-Org/Semantic-UI#3664) (fixed by #220)

## Global
  - [x] ~When a query will not match anything in any of the search bars we render `SearchEmptyResults`. If we click on the "clear query" button; the input field in the SearchBar is not cleared~ (see #226)
  - [x] Inconsistencies with the sorting order and the sorting filters (for instance some have both "Title A-Z" and "Asc/Desc"). Moreover not all occurrences of "Asc/Desc" seem to work (e.g. the one on the frontsite series page) (fixed by #214)
  - [x] ~The filters are not working as a user would expect. We can have multiple filters selected, for instance, we can select 2 different tags but we will only get the books that contain the last slected tag, instead of getting all the books with both tags~ (see #219) 
  - [x] ~`429` errors (too many requests) can be reached quickly when navigating on pages that perform multiple requests (current backend limitation is `100` requests per minute). Also there is no global handling of these errors as each component fail independently~ (see CERNDocumentServer/cds-ils#150)

_If needed, please edit this issue and extract some bullets into separate tickets._
