### ISSUE TITLE
UX and styling: backoffice forms 

### ISSUE THREAD

**Issue by kprzerwa** [inveniosoftware/react-invenio-app-ils#23]
- [x] Group fields into sections
  - Show only one section at a time to improve performance(?)
- [x] correct order fields in the forms
- [x] try to resemble the order on the details page to not confuse the user
another issues: 
- [x] When we are using a GroupField and we put together a dropdown (i.e. VocabularyField) and a simple 
 StringField they are not aligned correctly
- [x] Dropdown options are overlapping for example the DatePicker with inputs or the field that you select the currency. z-index that causes the problem, if we remove this the forms work as expected.
-  [x] Elasticsearch search components are taking the full width of the available space
-  [ ] Elasticsearch search components: is it possible to improve the display when a value is selected? it is currently not very visible, it is displayed below with a `x` to remove it.
