### ISSUE TITLE
forms: tasks

### ISSUE THREAD

**Issue by FlorianCassayre** [inveniosoftware/react-invenio-app-ils#286]
* **major**:
  - form validation errors can be returned from both backend & frontend; everything that can be validated by the client should be done that way (#243)
    * [ ] unify inputs error handling: that is fixing the inconsistency in the format between server and client errors, as described [here](https://github.com/inveniosoftware/react-invenio-app-ils/issues/243#issuecomment-722458242) (can be discussed)
    * [ ] implement the few missing yup schemas
    * [ ] verify that subforms are also validated (there is currently only one: the author field)
  * [ ] verify that error messages are displayed for each type of field; check that errors are displayed for groups. Fix console warnings related to error labels. There may be bugs in Semantic-UI itself (to be investigated)

* **minor**:
  * [x] input latency issues (#218)
  * [ ] vocabulary fields create one request per field (#213)
  * [ ] improve opening hours input UX, as explained [here](https://github.com/inveniosoftware/react-invenio-app-ils/pull/284#pullrequestreview-525270952)

* **enhancements** / **nice to have**:
  * [ ] disable the submit button when client validation fails. Server/network errors should not block the submit button!
  * [ ] currently client-side validation is triggered on submit; modify that to trigger it when on inputs that were blurred. Ensure it 
  works properly on the few dependent inputs (input groups/arrays, date/time periods, price field)
  * [ ] implement a cancel button (#178)
  * [ ] improve date range input (#200)
  * [ ] authors changes discarded when other author selected (#24)
  * [ ] prefill information when creating a document (#14)

**Comment by kprzerwa** [comment]
moved to react-json-schema-forms
